server {
    listen 80;
    listen [::]:80;
    server_name smalcouture.com;
    return 301 https://www.smalcouture.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name www.smalcouture.com;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        try_files $uri =404;
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://www.smalcouture.com$request_uri;
}
